/* eslint-disable */
// This file was generated by script
// this file is used to generate icon names from files within this directory
// icons are used in Icon component

import burger from './burger.svg';
import circleCheck from './circle-check.svg';
import closeMenu from './close-menu.svg';
import closeModal from './close-modal.svg';
import externalLink from './external-link.svg';
import playground from './playground.svg';
import socialDiscord from './social-discord.svg';
import socialX from './social-x.svg';
import treq from './treq.svg';

const icons = {
burger,
circleCheck,
closeMenu,
closeModal,
externalLink,
playground,
socialDiscord,
socialX,
treq,
};

export default icons;
